### ISSUE TITLE
Can't see plugin in menu

### ISSUE THREAD

**Issue by sudo-shubham** [KonstantinCodes/mautic-recaptcha#1]
I moved the MauticRecaptchaBundle directory of this repository to the plugins/ directory and clicked the "Install/Upgrade Plugins" button.
Still the plugin is not getting listed in the menu.

**Comment by KonstantinCodes** [comment]
@sudo-shubham Thanks for the Report. may I ask, which version of mautic youre using? and if you have cleared the production cache?

**Comment by sudo-shubham** [comment]
@KonstantinCodes Ohh.. I forgot to clear the cache. Thanks.
