### ISSUE TITLE
Multiple forms on the same site not working.

### ISSUE THREAD

**Issue by oexler** [KonstantinCodes/mautic-recaptcha#10]
Hi,
I have noticed that the plugin stops working when a reCaptcha field is inserted multiple times on a page. 
The problem is that the verifyCallback gets overridden. 
One solution would be to use "verifyCallback_{$formName}" as the callback name.

**Comment by Loilo** [comment]
See #11.

**Comment by oexler** [comment]
Hm. Ich weiss nicht ob es einen Vorteil hat md5 anstatt den Formularnamen zu verwenden. Macht das ganze nur etwas undurchsichtiger. Und es Funktioniert auch immernoch nicht wenn man 2x das gleich Formular verwendet.
Hatte am Anfang auch uniqid() verwenden wollen.
