### ISSUE TITLE
Plugin does not install with composer

### ISSUE THREAD

**Issue by Malbrouck** [KonstantinCodes/mautic-recaptcha#16]
Hi,

When I try to install this Mautic plugin I have this output from composer:

`# composer require koco/mautic-recaptcha-bundle
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version ^1.1 for koco/mautic-recaptcha-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
Package phpoffice/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpspreadsheet instead.
Generating autoload files
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

 // Clearing the cache for the prod environment with debug false

 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.

> php -r "if(file_exists('./.git')&&file_exists('./build/hooks/pre-commit'.(PHP_OS=='WINNT'?'.win':''))){copy('./build/hooks/pre-commit'.(PHP_OS=='WINNT'?'.win':''),'./.git/hooks/pre-commit');}"
> php -r "if(file_exists('./.git/hooks/pre-commit')&&(PHP_OS!='WINNT')){chmod('./.git/hooks/pre-commit',0755);}"`

Any clue why ?

**Comment by KonstantinCodes** [comment]
@Malbrouck thanks for the ticket. Can you please provide the output of the following commands?
`composer status --verbose`
`grep -A 15 koco/mautic-recaptcha-bundle composer.lock`
`ls -altr plugins/MauticRecaptchaBundle/`

Possibly try to remove and reinstall with:
`composer remove koco/mautic-recaptcha-bundle`
`rm -rf plugins/MauticRecaptchaBundle/`
`composer require koco/mautic-recaptcha-bundle`

**Comment by Malbrouck** [comment]
Hello,

I solved the problem and it had nothing to do with your plugin. For some reasons a .git directory was left inside the directory structure of another plugin. I deleted it and could successfully install your plugin.

Thank you very much for answering, for your help and for providing this plugin !

By the way, any plans to implement reCAPTCHA v3 ?

Cheers
