### ISSUE TITLE
add recaptcha v3 compatibility

### ISSUE THREAD

**Issue by BillyHilly** [KonstantinCodes/mautic-recaptcha#19]
Will this work with reCaptcha v2 AND v3? Or only v2?

**Comment by KonstantinCodes** [comment]
with v2

**Comment by dirtroof** [comment]
That's what I thought from testing, just wanted to be sure. Thanks for the quick response...AND this awesome plugin!

**Comment by godiez** [comment]
Hi @KonstantinCodes @BillyHilly , this issue might be closed, the plugin already supports recaptcha v3.
