### ISSUE TITLE
PlugIn will not install

### ISSUE THREAD

**Issue by incorak** [KonstantinCodes/mautic-recaptcha#3]
Hello!

Running Mautic v2.12.1 with a fairly standard installation on a linux server the plugin will not show up:
I unzipped the package and renamed the folder as mautic/plugins/MauticRecaptchaBundle  - with the plugin data (e.g. MauticRecaptchaBundle.php) in that folder the plugin won't install, i.e. it will not show up in the plugin list after clicking install/upgrade.
I did delete the cache and I do not use APC cache.

Is there anything else I have to consider: Obviously I am missing something, but the installation instructions are quite simple and straight-forward, so there must be something else to consider...

Thanks in advance for any advice.

Albrecht

**Comment by KonstantinCodes** [comment]
@incorak Thanks for the report. Can you please try the installation method via composer?

`composer require koco/mautic-recaptcha-bundle`

**Comment by KonstantinCodes** [comment]
closing due to no response
